"""Add soft delete tracking to customers

Revision ID: 8b792739b8b7
Revises: 511b57fc6088
Create Date: 2026-07-14 17:52:25.549002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b792739b8b7'
down_revision = '511b57fc6088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('customer_addresses_ibfk_1'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('idx_customer_id'))
        batch_op.drop_index(batch_op.f('idx_is_default'))
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('restored_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_loyalty_points'))
        batch_op.drop_index(batch_op.f('idx_phone'))
        batch_op.drop_index(batch_op.f('idx_tier'))
        batch_op.create_foreign_key(None, 'employees', ['deleted_by'], ['id'])

    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('loyalty_transactions_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('loyalty_transactions_ibfk_2'), type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_customer_id'))
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'employees', ['processed_by'], ['id'])

    with op.batch_alter_table('system_access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_employee_id'))
        batch_op.drop_index(batch_op.f('idx_session_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loyalty_transactions_ibfk_1'), 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('loyalty_transactions_ibfk_2'), 'employees', ['processed_by'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('idx_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('idx_loyalty_points'), ['loyalty_points'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('restored_at')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('customer_addresses_ibfk_1'), 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('idx_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###
